### PR TITLE
adding CI files for publishing to PyPI and TestPyPI

### PR DESCRIPTION
**Pull request by jmxpearson**
Will upload to `test.pypi.org` on any `push` to `main` and to `pypi.org` on any tag push of the form `v[0-9]*`.

### CODE REVIEW

**Comment by jmxpearson** [comment]
@draelos, I think the test will pass once I have access on `test.pypi.org` and can set up trusted publishing there.

**Comment by jmxpearson** [comment]
Closes #99

**Comment by jmxpearson** [comment]
Ok, according to [this StackOverflow question](https://stackoverflow.com/questions/54887301/how-can-i-use-git-repos-as-dependencies-for-my-pypi-package), we can’t have direct dependencies that are GitHub repos. So we’ll need to also release Bubblewrap to PyPI in order to have the optional dependency in `pyproject.toml`. 

Alternately, we could just use a `requirements.txt` file in the demo folder as we’ve discussed with the other demos. That’s probably my preferred solution in this case.

**Review by draelos — APPROVED** [review]
Changes look good to me (thanks for updating my email!), minimal demo works, and tests all pass.

**Pull request merged**
