### PR TITLE
simple fastplotlib example

### LINKED ISSUE #85: using improv with fastplotlib for visualization
I've been playing around with this for the past week and I have some questions and a possible issue.

1. This line prevents `nexus.startNexus()` from being run within a jupyter notebook, it seems like jupyter has its own `asyncio` running:

https://github.com/project-improv/improv/blob/763f0d871268397318399a9f6f8ea6fcae49d697/improv/nexus.py#L181

This is what I get when I try to call `nexus.startNexus()` within jupyter. Various workarounds suggested [here](https://github.com/ipython/ipython/issues/11338) such as `%autoawait off` or [this](https://github.com/ipython/ipython/issues/11338#issuecomment-646539516) make the `startNexus()` call blocking which is not what we want. 

Note that the line numbers in the traceback don't match your dev branch because I added some comments, line 184 in the traceback is 181 in your dev branch. 

```python
improv.nexus Starting processes
improv.nexus <ForkProcess name='Generator' parent=2441387 initial daemon>
improv.nexus <ForkProcess name='Processor' parent=2441387 initial daemon>
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[3], line 1
----> 1 n.startNexus()

File ~/Insync/kushalkolar@gmail.com/drive/repos/improv/improv/nexus.py:184, in Nexus.startNexus(self)
    180     loop.add_signal_handler(
    181         s, lambda s=s: self.stop_polling(s, loop)) #TODO
    182 try:
    183     # This does not work with jupyter
--> 184     res = loop.run_until_complete(self.pollQueues()) #TODO: in Link executor, complete all tasks
    185 except asyncio.CancelledError:
    186     logging.info("Loop is cancelled")

File /usr/lib/python3.10/asyncio/base_events.py:622, in BaseEventLoop.run_until_complete(self, future)
    611 """Run until the Future is done.
    612 
    613 If the argument is a coroutine, it is wrapped in a Task.
   (...)
    619 Return the Future's result, or raise its exception.
    620 """
    621 self._check_closed()
--> 622 self._check_running()
    624 new_task = not futures.isfuture(future)
    625 future = tasks.ensure_future(future, loop=self)

File /usr/lib/python3.10/asyncio/base_events.py:582, in BaseEventLoop._check_running(self)
    580 def _check_running(self):
    581     if self.is_running():
--> 582         raise RuntimeError('This event loop is already running')
    583     if events._get_running_loop() is not None:
    584         raise RuntimeError(
    585             'Cannot run the event loop while another loop is running')

RuntimeError: This event loop is already running
```

To get a prototype working I just added a `return` after the `start()` call here: https://github.com/kushalkolar/improv/commit/1efaa114d1da157e832416d33770cafcf96a331c#diff-5572e082ebe8c66e061e05fea29c3eaec5036c7af0c9fd8ca273f245e97614e0R173 

2. I made a visualization demo based on `minimal` and it seems to kind of work: https://github.com/kushalkolar/improv/tree/dev/demos/fastplotlib 

### Questions:

1. How do I remove an item from a `q_in` or `q_out` to free up RAM?
2. In the current example all I'm doing is the `Generator` actor is producing random data which is being received and plotted in the current kernel (and not from within an actor). I think the overhead for the remote frame buffer widget is quite low so I would like to use it like this for now.
    - In the future I could potentially create an `Actor` to manage the remote frame buffer (or multiple remote frame buffers) for visualizations, but from my experience it is quite fast that I don't see that this is necessary. I'd have to dig into the WGPU canvases quite a bit to figure out how to do that.
    - An alternative is to start a ipython kernel which can be connected to from a jupyter notebook and is able to access the queues and get items.
3. I think the best way I see this being use for visualization is that we have actors that perform preprocessing (OnACID or behavior, etc) or analysis, and each of these actors dump data into a "visualization queue" that we can access from the jupyter kernel.
    - For calcium imaging & behavior we can just show the most recently added frame, keep the queue size as 1.
    - For other visualizations (neural activity for example) we can just use a FIFO queue to append to an existing visualization.

By the way it'd be useful if the codebase uses type annotations, makes it easier for newcomers to navigate :smile: (hope I'm not stepping on any toes here, I still can't figure out what type of object `q_in` and `q_out` are)

### PR DESCRIPTION
**Pull request by kushalkolar**
very simple example with fastplotlib to show updating frames with randomly generated data.

Closes #85 

The jupyterlab server is running on my lab workstation but I'm connecting to it from home just through my browser so the remote frame buffer is being streamed over the internet.

https://user-images.githubusercontent.com/9403332/226087864-060a101c-8685-453c-912b-d56d4ac7b0f4.mp4

Basically:

Generator: 512 x 512 random frames  -> queue -> Processor, sends zmq message

jupyter notebook: receives zmq message, updates image graphic in fastplotlib

https://github.com/kushalkolar/improv/blob/fastplotlib-demo/demos/fastplotlib/fastplotlib.ipynb

### CODE REVIEW

**Comment by jmxpearson** [comment]
This is really cool! I'm going to ask that we wait on merging this until @draelos finishes her review and we merge `tui` into `dev`. At that point, we should only need to change the way the demo is invoked. Should be doable in the next week, I think.

I will also want us to think about how we write a test for this. I don't want/need full coverage for demos, but it would be good to have ways to check we aren't breaking them in future, especially since lots of people may want this feature.

**Comment by kushalkolar** [comment]
Sure! I mostly wanted to make sure that this is the right way to approach sending data to notebooks.

Looking into testing notebooks, this looks like it should work: https://github.com/treebeardtech/nbmake 

I'll have to make sure the tests actually execute in the notebook, some of the other jupyter notebook testing options just extract the code and run it in a regular python kernel. When `wgpu-py` doesn't detect that it's in a notebook context it will start a `glfw` or `Qt` event loop to run the plot as a desktop application.

**Comment by draelos** [comment]
I'm not sure calling improv server on a .ipynb file works anyway? But the first error is likely due to what John mentioned. The file global.log should have more traceback.

**Comment by jmxpearson** [comment]
Correct. You’d need to do ```improv server <config yaml>```and then use `zmq` inside the notebook (connecting on the ports the server outputs) to send the `setup`, `run`, etc. commands.On Mar 22, 2023, at 17:15, Anne Draelos ***@***.***> wrote:﻿
I'm not sure calling improv server on a .ipynb file works anyway? But the first error is likely due to what John mentioned. The file global.log should have more traceback.

**Comment by kushalkolar** [comment]
continued in #104

**Pull request closed without merging**
